config/routes.rb
Krog::Application.routes.draw do
	resources :todos

	resources :countries

	resources :reviewers

	resources :reviews

	resources :beers

	resources :people

	resources :sorts

	resources :sound_levels

	resources :hygienes

	resources :clienteles

	resources :categories

	resources :hours

	resources :establishments

	root :to => "establishments#index"

end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
	belongs_to :person
	belongs_to :review
end

app/controllers/reviewers_controller.rb
class ReviewersController < ApplicationController
	# GET /reviewers
	# GET /reviewers.xml
	def index
		@reviewers = Reviewer.all

		respond_to do |format|
			format.html # index.html.erb
			format.xml  { render :xml => @reviewers }
		end
	end

	# GET /reviewers/1
	# GET /reviewers/1.xml
	def show
		@reviewer = Reviewer.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.xml  { render :xml => @reviewer }
		end
	end

	# GET /reviewers/new
	# GET /reviewers/new.xml
	def new
		@reviewer = Reviewer.new

		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @reviewer }
		end
	end

	# GET /reviewers/1/edit
	def edit
		@reviewer = Reviewer.find(params[:id])
	end

	# POST /reviewers
	# POST /reviewers.xml
	def create
		@reviewer = Reviewer.new(params[:reviewer])

		respond_to do |format|
			if @reviewer.save
				format.html { redirect_to(@reviewer, :notice => 'Reviewer was successfully created.') }
				format.xml  { render :xml => @reviewer, :status => :created, :location => @reviewer }
			else
				format.html { render :action => "new" }
				format.xml  { render :xml => @reviewer.errors, :status => :unprocessable_entity }
			end
		end
	end

	# PUT /reviewers/1
	# PUT /reviewers/1.xml
	def update
		@reviewer = Reviewer.find(params[:id])

		respond_to do |format|
			if @reviewer.update_attributes(params[:reviewer])
				format.html { redirect_to(@reviewer, :notice => 'Reviewer was successfully updated.') }
				format.xml  { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml  { render :xml => @reviewer.errors, :status => :unprocessable_entity }
			end
		end
	end

	# DELETE /reviewers/1
	# DELETE /reviewers/1.xml
	def destroy
		@reviewer = Reviewer.find(params[:id])
		@reviewer.destroy

		respond_to do |format|
			format.html { redirect_to(reviewers_url) }
			format.xml  { head :ok }
		end
	end
end

app/views/reviewers/_form.html.haml
= form_for(@reviewer) do |f|
	- if @reviewer.errors.any?
		#error_explanation
			%h2 #{ pluralize(@reviewer.errors.count, "error") } prohibited this reviewer from being saved:
			%ul
				- @reviewer.errors.full_messages.each do |msg|
					%li= msg

	.field
		= f.label :person
		%br
		= f.text_field :person
	
	.field
		= f.label :review
		%br
		= f.text_field :review
	
	.actions
		= f.submit

app/views/reviewers/edit.html.haml
%h1 Editing reviewer

= render 'form'

= link_to 'Show', @reviewer
|
= link_to 'Back', reviewers_path

app/views/reviewers/index.html.haml
%h1 Listing reviewers

%table
	%tr
		%th Person
		%th Review
		%th
		%th
		%th

- @reviewers.each do |reviewer|
	%tr
		%td= reviewer.person
		%td= reviewer.review
		%td= link_to 'Show', reviewer
		%td= link_to 'Edit', edit_reviewer_path(reviewer)
		%td= link_to 'Destroy', reviewer, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Reviewer', new_reviewer_path

app/views/reviewers/new.html.haml
%h1 New reviewer

= render 'form'

= link_to 'Back', reviewers_path

app/views/reviewers/show.html.haml
%p#notice= notice

%p
	%b Person:
	= @reviewer.person
	
%p
	%b Review:
	= @reviewer.review

= link_to 'Edit', edit_reviewer_path(@reviewer)
|
= link_to 'Back', reviewers_path