config/routes.rb
Krog::Application.routes.draw do
	resources :todos

	resources :countries

	resources :reviewers

	resources :reviews

	resources :beers

	resources :people

	resources :sorts

	resources :sound_levels

	resources :hygienes

	resources :clienteles

	resources :categories

	resources :hours

	resources :establishments

	root :to => "establishments#index"

end

app/models/clientele.rb
class Clientele < ActiveRecord::Base
	has_many :reviews
end

app/controllers/clienteles_controller.rb
class ClientelesController < ApplicationController
	# GET /clienteles
	# GET /clienteles.xml
	def index
		@clienteles = Clientele.all

		respond_to do |format|
			format.html # index.html.erb
			format.xml  { render :xml => @clienteles }
		end
	end

	# GET /clienteles/1
	# GET /clienteles/1.xml
	def show
		@clientele = Clientele.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.xml  { render :xml => @clientele }
		end
	end

	# GET /clienteles/new
	# GET /clienteles/new.xml
	def new
		@clientele = Clientele.new

		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @clientele }
		end
	end

	# GET /clienteles/1/edit
	def edit
		@clientele = Clientele.find(params[:id])
	end

	# POST /clienteles
	# POST /clienteles.xml
	def create
		@clientele = Clientele.new(params[:clientele])

		respond_to do |format|
			if @clientele.save
				format.html { redirect_to(@clientele, :notice => 'Clientele was successfully created.') }
				format.xml  { render :xml => @clientele, :status => :created, :location => @clientele }
			else
				format.html { render :action => "new" }
				format.xml  { render :xml => @clientele.errors, :status => :unprocessable_entity }
			end
		end
	end

	# PUT /clienteles/1
	# PUT /clienteles/1.xml
	def update
		@clientele = Clientele.find(params[:id])

		respond_to do |format|
			if @clientele.update_attributes(params[:clientele])
				format.html { redirect_to(@clientele, :notice => 'Clientele was successfully updated.') }
				format.xml  { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml  { render :xml => @clientele.errors, :status => :unprocessable_entity }
			end
		end
	end

	# DELETE /clienteles/1
	# DELETE /clienteles/1.xml
	def destroy
		@clientele = Clientele.find(params[:id])
		@clientele.destroy

		respond_to do |format|
			format.html { redirect_to(clienteles_url) }
			format.xml  { head :ok }
		end
	end
end

app/views/clienteles/_form.html.haml
= form_for(@clientele) do |f|
	- if @clientele.errors.any?
		#error_explanation
			%h2 #{ pluralize(@clientele.errors.count, "error") } prohibited this clientele from being saved:
			%ul 
				- @clientele.errors.full_messages.each do |msg|
					%li= msg
		
	.field
		= f.label :name
		%br
		= f.text_field :name

	.actions
		= f.submit

app/views/clienteles/edit.html.haml
%h1 Editing clientele

= render 'form'

= link_to 'Show', @clientele
|
= link_to 'Back', clienteles_path

app/views/clienteles/index.html.haml
%h1 Listing clienteles

%table
	%tr
		%th Name
		%th
		%th
		%th

- @clienteles.each do |clientele|
	%tr 
		%td= clientele.name
		%td= link_to 'Show', clientele
		%td= link_to 'Edit', edit_clientele_path(clientele)
		%td= link_to 'Destroy', clientele, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Clientele', new_clientele_path

app/views/clienteles/new.html.haml
%h1 New clientele

= render 'form'

= link_to 'Back', clienteles_path

app/views/clienteles/show.html.haml
%p#notice= notice

%p 
	%b Name:
	= @clientele.name

= link_to 'Edit', edit_clientele_path(@clientele)
|
= link_to 'Back', clienteles_path