config/routes.rb
Krog::Application.routes.draw do
	resources :todos

	resources :countries

	resources :reviewers

	resources :reviews

	resources :beers

	resources :people

	resources :sorts

	resources :sound_levels

	resources :hygienes

	resources :clienteles

	resources :categories

	resources :hours

	resources :establishments

	root :to => "establishments#index"

end

app/models/establishment.rb
class Establishment < ActiveRecord::Base
	has_many :reviews
	belongs_to :category
	belongs_to :opening_hour, :class_name => "Hour", :foreign_key => "opening_hour_id"
	belongs_to :closing_hour, :class_name => "Hour", :foreign_key => "closing_hour_id"
	belongs_to :tapped_beer, :class_name => "Beer", :foreign_key => "tapped_beer_id"
	belongs_to :bottled_beer, :class_name => "Beer", :foreign_key => "bottled_beer_id"

	accepts_nested_attributes_for :opening_hour, :closing_hour, :tapped_beer, :bottled_beer, :allow_destroy => :true ,  :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

	def self.search (value)
		value[:category]
		value[:rating]
		value[:closing_hour]
		value[:opening_hour]
		value[:tapped_beer]
		value[:bottled_beer]
		value[:age_limit]
		value[:locale]
		value[:city]
	end

	def average_rating
		reviews.joins(:rating).average('ratings.value')
	end
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
	# GET /establishments
	# GET /establishments.xml
	def index
	@establishments = Establishment.all :include => {:reviews => :rating}

		respond_to do |format|
			format.html # index.html.erb
			format.xml  { render :xml => @establishments }
		end
	end

	# GET /establishments/1
	# GET /establishments/1.xml
	def show
		@establishment = Establishment.find(params[:id], :include => {:reviews => :rating})
		@reviews = @establishment.reviews

		respond_to do |format|
			format.html # show.html.erb
			format.xml  { render :xml => @establishment }
		end
	end

	# GET /establishments/new
	# GET /establishments/new.xml
	def new
		@establishment = Establishment.new
		@establishment.tapped_beer = Beer.new
		@establishment.bottled_beer = Beer.new
		
		@establishment.opening_hour = Hour.new
		@establishment.closing_hour = Hour.new
		
		@beers = Beer.all
		@categories = Category.all

		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @establishment }
		end
	end

	# GET /establishments/1/edit
	def edit
		@establishment = Establishment.find(params[:id])
	end

	# POST /establishments
	# POST /establishments.xml
	def create
		@establishment = Establishment.new(params[:establishment])
		@establishment.tapped_beer = Beer.find(params[:tapped_beer])
		@establishment.bottled_beer = Beer.find(params[:bottled_beer])
		@establishment.category = Category.find(params[:category])

		@establishment.closing_hour = Hour.parse(params[:closing_hour])
		@establishment.opening_hour = Hour.parse(params[:opening_hour])

		respond_to do |format|
			if @establishment.save
				format.html { redirect_to(@establishment, :notice => 'Establishment was successfully created.') }
				format.xml  { render :xml => @establishment, :status => :created, :location => @establishment }
			else
				format.html { render :action => "new" }
				format.xml  { render :xml => @establishment.errors, :status => :unprocessable_entity }
			end
		end
	end

	# PUT /establishments/1
	# PUT /establishments/1.xml
	def update
		@establishment = Establishment.find(params[:id])

		respond_to do |format|
			if @establishment.update_attributes(params[:establishment])
				format.html { redirect_to(@establishment, :notice => 'Establishment was successfully updated.') }
				format.xml  { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml  { render :xml => @establishment.errors, :status => :unprocessable_entity }
			end
		end
	end

	# DELETE /establishments/1
	# DELETE /establishments/1.xml
	def destroy
		@establishment = Establishment.find(params[:id])
		@establishment.destroy

		respond_to do |format|
			format.html { redirect_to(establishments_url) }
			format.xml  { head :ok }
		end
	end
end

app/views/establishments/_form.html.haml
= form_for(@establishment) do |f|
	- if @establishment.errors.any?
		#error_explanation
			%h2 #{ pluralize(@establishment.errors.count, "error") } prohibited this establishment from being saved:
			%ul
				- @establishment.errors.full_messages.each do |msg|
					%li= msg

	.field
		= f.label :name
		%br
		= f.text_field :name

	.field
		= f.label :locale
		%br
		= f.text_field :locale

	.field
		= f.label :city
		%br
		= f.text_field :city

	.field
		= f.label :wardrobe_fee
		%br
		= f.text_field :wardrobe_fee

	.field
		= f.label :entrance_fee
		%br
		= f.text_field :entrance_fee

	.field
		= f.label :entrance_fee_start
		%br
		= f.time_select :entrance_fee_start

	.field
		= f.label :comment
		%br
		= f.text_area :comment

	.field
		= f.label :age_limit
		%br
		= f.text_field :age_limit

	.field
		= f.label :category
		%br
		= select_tag :category, options_from_collection_for_select(@categories, "id", "name")

	.field
		= f.fields_for :tapped_beer do |tapped_beer_form|
			= tapped_beer_form.label :tapped_beer
			= f.label "price"
			%br
			= select_tag :tapped_beer, options_from_collection_for_select(@beers, "id", "name")
			= f.text_field :tapped_beer_price, :size => 3

	.field
		= f.fields_for :bottled_beer do |tapped_beer_form|
			= tapped_beer_form.label :bottled_beer
			= f.label "price"
			%br
			= select_tag :bottled_beer, options_from_collection_for_select(@beers, "id", "name")
			= f.text_field :bottled_beer_price, :size => 3


	.field
		= fields_for :closing_hour do |closing_hour_form|
			Closing Hour:
			%br
			.week_fields
				= label_tag :weekday, "Weekday (Su-Th)"
				= label_tag :weekend, "Weekend (Fr-Sa)"
				%br
				= closing_hour_form.time_select :weekday, :minute_step => 30, :ignore_date => true
				= closing_hour_form.time_select :weekend, :minute_step => 30, :ignore_date => true

			= render "hour_fields", :form => closing_hour_form, :cls => "closing_hour"

	.field
		= fields_for :opening_hour do |opening_hour_form|
			Opening Hour:
			%br
			.week_fields
				= label_tag :weekday, "Weekday (Su-Th)"
				= label_tag :weekend, "Weekend (Fr-Sa)"
				%br
				= opening_hour_form.time_select :weekday, :minute_step => 30, :ignore_date => true
				= opening_hour_form.time_select :weekend, :minute_step => 30, :ignore_date => true

			= render "hour_fields", :form => opening_hour_form, :cls => "opening_hour"

	.field
		= link_to "Toggle advanced fields", "#", :id => "toggle_advanced_fields"

	.actions
		= f.submit

app/views/establishments/_hour_fields.html.haml
.advanced_fields
	=form.label "Monday" 
	=form.time_select :monday, { :minute_step => 30, :ignore_date => true }, :class => cls + "_weekday" 
	%br
	
	=form.label "Tuesday" 
	=form.time_select :tuesday, { :minute_step => 30, :ignore_date => true }, :class => cls + "_weekday" 
	%br
	
	=form.label "Wednesday" 
	=form.time_select :wednesday, { :minute_step => 30, :ignore_date => true }, :class => cls + "_weekday" 
	%br
	
	=form.label "Thursday" 
	=form.time_select :thursday, { :minute_step => 30, :ignore_date => true }, :class => cls + "_weekday" 
	%br
	
	=form.label "Friday" 
	=form.time_select :friday, { :minute_step => 30, :ignore_date => true }, :class => cls + "_weekend" 
	%br
	
	
	=form.label "Saturday" 
	=form.time_select :saturday, { :minute_step => 30, :ignore_date => true }, :class => cls + "_weekend" 
	%br
	
	=form.label "Sunday" 
	=form.time_select :sunday, { :minute_step => 30, :ignore_date => true }, :class => cls + "_weekday"

app/views/establishments/_list.html.haml
%table.tableListing
	%tr
		%th Name
		%th Locale
		%th City
		%th Age limit
		%th Category
		%th Rating
		%th Bottled Beer
		%th Tapped Beer
		%th Wardrobe fee
		%th Entrance fee
		%th Entrance fee start
		%th Comment
		%th
		%th
		%th

	- @establishments.each do |establishment|
		%tr
			%td= establishment.name
			%td= establishment.locale
			%td= establishment.city
			%td= establishment.age_limit
			%td= establishment.category.name
			%td= establishment.average_rating
			%td= establishment.bottled_beer.name
			%td= establishment.tapped_beer.name
			%td= establishment.wardrobe_fee
			%td= establishment.entrance_fee
			%td= establishment.entrance_fee_start
			%td= establishment.comment
			%td= link_to 'Show', establishment
			%td= link_to 'Edit', edit_establishment_path(establishment)
			%td= link_to 'Destroy', establishment, :confirm => 'Are you sure?', :method => :delete

app/views/establishments/edit.html.haml
%h1 Editing establishment

= render 'form'

= link_to 'Show', @establishment
|
= link_to 'Back', establishments_path

app/views/establishments/index.html.haml
%h1 Listing establishments

= render 'establishments/list'

%br

= link_to 'New Establishment', new_establishment_path

app/views/establishments/new.html.haml
%h1 New establishment

= render 'form'

= link_to 'Back', establishments_path

app/views/establishments/show.html.haml
%p#notice= notice

%p
	%b Name:
	= @establishment.name 

%p
	%b Locale:
	= @establishment.locale 

%p
	%b City:
	= @establishment.city 

%p
	%b Age limit:
	= @establishment.age_limit 

%p
	%b Category:
	= link_to @establishment.category.name, @establishment.category 

%p
	%b Rating:
	= @establishment.average_rating 

%p
	%b Bottled Beer:
	= @establishment.bottled_beer.name 

%p
	%b Tapped Beer:
	= @establishment.tapped_beer.name 

%p
	%b Opening Hours:
	= @establishment.opening_hour.to_day 

%p
	%b Closing Hours:
	= @establishment.closing_hour.to_day 

%p
	%b Wardrobe fee:
	= @establishment.wardrobe_fee 

%p
	%b Entrance fee:
	= @establishment.entrance_fee 

%p
	%b Entrance fee start:
	= @establishment.entrance_fee_start 

%p
	%b Comment:
	= @establishment.comment 

= link_to 'Edit', edit_establishment_path(@establishment)
|
= link_to 'Back', establishments_path
|
= link_to 'New Review', new_review_path 

= render 'reviews/list' 